//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Globals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Globals", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is null..
        /// </summary>
        internal static string Address_is_null {
            get {
                return ResourceManager.GetString("Address_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention is null..
        /// </summary>
        internal static string Attention_is_null {
            get {
                return ResourceManager.GetString("Attention_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a file..
        /// </summary>
        internal static string Choose_a_file {
            get {
                return ResourceManager.GetString("Choose_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose cost equal total cost..
        /// </summary>
        internal static string Choose_equal_cost {
            get {
                return ResourceManager.GetString("Choose_equal_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose file size less than 10 megabytes..
        /// </summary>
        internal static string Choose_file_size {
            get {
                return ResourceManager.GetString("Choose_file_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose full 100 percent..
        /// </summary>
        internal static string Choose_full_100_percent {
            get {
                return ResourceManager.GetString("Choose_full_100_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose cost less than total cost..
        /// </summary>
        internal static string Choose_less_than_cost {
            get {
                return ResourceManager.GetString("Choose_less_than_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose less than 100 percent..
        /// </summary>
        internal static string Choose_less_than_percent {
            get {
                return ResourceManager.GetString("Choose_less_than_percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose less than 12  term..
        /// </summary>
        internal static string Choose_less_than_term {
            get {
                return ResourceManager.GetString("Choose_less_than_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose only jpg, png, gif, rtf, doc, docx, xls, xlsx, or pdf file..
        /// </summary>
        internal static string Choose_only_file {
            get {
                return ResourceManager.GetString("Choose_only_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentFactory.
        /// </summary>
        internal static string ComponentFactory {
            get {
                return ResourceManager.GetString("ComponentFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert Customer Name Thai or Eng.
        /// </summary>
        internal static string CustomerNameTHEN {
            get {
                return ResourceManager.GetString("CustomerNameTHEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null..
        /// </summary>
        internal static string Customer_is_null {
            get {
                return ResourceManager.GetString("Customer_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaoFactory.
        /// </summary>
        internal static string DaoFactory {
            get {
                return ResourceManager.GetString("DaoFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data duplication..
        /// </summary>
        internal static string Data_duplication {
            get {
                return ResourceManager.GetString("Data_duplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete succeed..
        /// </summary>
        internal static string Delete_succeed {
            get {
                return ResourceManager.GetString("Delete_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Email Account for.
        /// </summary>
        internal static string EmailAccount_is_empty {
            get {
                return ResourceManager.GetString("EmailAccount_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date..
        /// </summary>
        internal static string End_date_greater_than_start {
            get {
                return ResourceManager.GetString("End_date_greater_than_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityFactory.
        /// </summary>
        internal static string EntityFactory {
            get {
                return ResourceManager.GetString("EntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ราคาต้องไม่ต่ำกว่า 500,000 บาท.
        /// </summary>
        internal static string FiveHundredThousand {
            get {
                return ResourceManager.GetString("FiveHundredThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is null..
        /// </summary>
        internal static string Group_is_null {
            get {
                return ResourceManager.GetString("Group_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id invalid..
        /// </summary>
        internal static string Id_invalid {
            get {
                return ResourceManager.GetString("Id_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id not found..
        /// </summary>
        internal static string Id_not_found {
            get {
                return ResourceManager.GetString("Id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id to delete..
        /// </summary>
        internal static string Invalid_id_to_delete {
            get {
                return ResourceManager.GetString("Invalid_id_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id to update..
        /// </summary>
        internal static string Invalid_id_to_update {
            get {
                return ResourceManager.GetString("Invalid_id_to_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string Invalid_username_or_password {
            get {
                return ResourceManager.GetString("Invalid_username_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu is null..
        /// </summary>
        internal static string Menu_is_null {
            get {
                return ResourceManager.GetString("Menu_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to delete..
        /// </summary>
        internal static string No_data_to_delete {
            get {
                return ResourceManager.GetString("No_data_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent ID not found..
        /// </summary>
        internal static string Parent_id_not_found {
            get {
                return ResourceManager.GetString("Parent_id_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter attention..
        /// </summary>
        internal static string Please_enter_attention {
            get {
                return ResourceManager.GetString("Please_enter_attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter code..
        /// </summary>
        internal static string Please_enter_code {
            get {
                return ResourceManager.GetString("Please_enter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกราคา.
        /// </summary>
        internal static string Please_enter_cost {
            get {
                return ResourceManager.GetString("Please_enter_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter customer..
        /// </summary>
        internal static string Please_enter_customer {
            get {
                return ResourceManager.GetString("Please_enter_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter date value..
        /// </summary>
        internal static string Please_enter_date {
            get {
                return ResourceManager.GetString("Please_enter_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกฝ่าย.
        /// </summary>
        internal static string Please_enter_department {
            get {
                return ResourceManager.GetString("Please_enter_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no..
        /// </summary>
        internal static string Please_enter_no {
            get {
                return ResourceManager.GetString("Please_enter_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to กรุณากรอกชื่อโครงการ (ไทย).
        /// </summary>
        internal static string Please_enter_project_thainame {
            get {
                return ResourceManager.GetString("Please_enter_project_thainame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter year..
        /// </summary>
        internal static string Please_enter_year {
            get {
                return ResourceManager.GetString("Please_enter_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portion is null..
        /// </summary>
        internal static string Portion_is_nul {
            get {
                return ResourceManager.GetString("Portion_is_nul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portion is null..
        /// </summary>
        internal static string Portion_is_null {
            get {
                return ResourceManager.GetString("Portion_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuoDetail is null..
        /// </summary>
        internal static string QuoDetail_is_null {
            get {
                return ResourceManager.GetString("QuoDetail_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succeed..
        /// </summary>
        internal static string Save_succeed {
            get {
                return ResourceManager.GetString("Save_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mail Error.
        /// </summary>
        internal static string SendEmail_error {
            get {
                return ResourceManager.GetString("SendEmail_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Mail Success.
        /// </summary>
        internal static string SendEmail_success {
            get {
                return ResourceManager.GetString("SendEmail_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site is null..
        /// </summary>
        internal static string Site_is_null {
            get {
                return ResourceManager.GetString("Site_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 789699CEF11437449767A30F010A98D0.
        /// </summary>
        internal static string Site_Quotation {
            get {
                return ResourceManager.GetString("Site_Quotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status invalid..
        /// </summary>
        internal static string Status_invalid {
            get {
                return ResourceManager.GetString("Status_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term of payment is null..
        /// </summary>
        internal static string Term_payment_is_null {
            get {
                return ResourceManager.GetString("Term_payment_is_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update succeed..
        /// </summary>
        internal static string Update_succeed {
            get {
                return ResourceManager.GetString("Update_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File uploaded successfully..
        /// </summary>
        internal static string Uploaded_successfully {
            get {
                return ResourceManager.GetString("Uploaded_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is empty..
        /// </summary>
        internal static string Username_or_password_is_empty {
            get {
                return ResourceManager.GetString("Username_or_password_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t use this website.
        /// </summary>
        internal static string UserNoPermission {
            get {
                return ResourceManager.GetString("UserNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT is null..
        /// </summary>
        internal static string VAT_is_null {
            get {
                return ResourceManager.GetString("VAT_is_null", resourceCulture);
            }
        }
    }
}
