//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBase.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Globals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Globals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectBase.Web.Resources.Globals", typeof(Globals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComponentFactory.
        /// </summary>
        internal static string ComponentFactory {
            get {
                return ResourceManager.GetString("ComponentFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DaoFactory.
        /// </summary>
        internal static string DaoFactory {
            get {
                return ResourceManager.GetString("DaoFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete succeed..
        /// </summary>
        internal static string Delete_succeed {
            get {
                return ResourceManager.GetString("Delete_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityFactory.
        /// </summary>
        internal static string EntityFactory {
            get {
                return ResourceManager.GetString("EntityFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid id to delete..
        /// </summary>
        internal static string Invalid_id_to_delete {
            get {
                return ResourceManager.GetString("Invalid_id_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to delete..
        /// </summary>
        internal static string No_data_to_delete {
            get {
                return ResourceManager.GetString("No_data_to_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save succeed..
        /// </summary>
        internal static string Save_succeed {
            get {
                return ResourceManager.GetString("Save_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update succeed..
        /// </summary>
        internal static string Update_succeed {
            get {
                return ResourceManager.GetString("Update_succeed", resourceCulture);
            }
        }
    }
}
